databases:
  - name: SourceZe 
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: SourceZe
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m ELHYBA.py
    region: frankfurt
    envVars:
      - key: ELHYBA
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DATABASE_URL
    autoDeploy: false
